### ISSUE TITLE
Transition of project ownership

### ISSUE THREAD

**Issue by mike442144** [sylvinus/node-crawler#168]
Please just use my [node-webcrawler](https://github.com/bda-research/node-webcrawler) instead, because the current author won't maintain crawler any more and didn't transfer the repo to any others, I have fixed several critical bugs and will continue to maintain it. I'll continue to make it the best crawler in nodejs world.

**Comment by sylvinus** [comment]
Hi guys,

As @mike442144 pointed out I have no time to maintain this project anymore.

If there are a no objections to it for the next 7 days, I'll transfer this repository as well as the npm module to him as he assured me he's willing to maintain the module and welcome new developer contributions.

If you have any specific concerns or guidance for the transition please explain them here!

I think it would be a healthy time to do a major version bump so that the history is clear on npm, but I'll let that to the future maintainers as well.

**Comment by paulvalla** [comment]
Fine with me, good luck new maintainer !

**Comment by sylvinus** [comment]
Okay! Let's do it!

Thanks @mike442144 for stepping up and good luck! Feel free to reach out if you need any help.
